version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-leon
    ports:
      - "30678:30678"
    env_file:
      - .env
    volumes:
      - ./certs:/app/certs:ro
    networks:
      - default
    external_links:
      - my-postgres:postgres
    restart: always
